server:
  port: 80
  servlet:
    context-path: /contacts
spring:
  application:
    name: Contacts
  servlet:
    multipart:
      enabled: false
      max-file-size: -1
      max-request-size: -1
  profiles:
    include:
      - local
      # - release